[package]
name = "dpimyass"
version = "1.0.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_with = "3.5.0"
toml = "0.8"
