[package]
name = "udpmyass"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
udp-stream = "0.0.10"
tokio = { version = "1", features = ["full", "sync", "net", "macros", "io-util"] }
